# Generated by Django 2.2.3 on 2019-07-28 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(db_column='custId', primary_key=True, serialize=False)),
                ('custname', models.TextField(blank=True, db_column='custName', null=True)),
                ('custaddress', models.TextField(blank=True, db_column='custAddress', null=True)),
                ('custcontact', models.CharField(blank=True, db_column='custContact', max_length=50, null=True)),
                ('custemail', models.CharField(blank=True, db_column='custEmail', max_length=140, null=True)),
                ('custisactive', models.CharField(choices=[('y', 'y'), ('n', 'n')], db_column='custIsActive', max_length=1)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domainid', models.AutoField(db_column='domainId', primary_key=True, serialize=False)),
                ('domainaddress', models.CharField(blank=True, db_column='domainAddress', max_length=250, null=True)),
                ('domainrefcustid', models.ForeignKey(blank=True, db_column='domainRefCustId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Customer')),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(db_column='personId', primary_key=True, serialize=False)),
                ('personname', models.CharField(blank=True, db_column='personName', max_length=100, null=True)),
                ('personcontacttype', models.CharField(blank=True, db_column='personContactType', max_length=5, null=True)),
                ('personcontact', models.CharField(blank=True, db_column='personContact', max_length=100, null=True)),
                ('personactive', models.CharField(choices=[('y', 'y'), ('n', 'n')], db_column='personActive', max_length=1)),
                ('personrefcustid', models.ForeignKey(blank=True, db_column='personRefCustId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Customer')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('woid', models.AutoField(db_column='woId', primary_key=True, serialize=False)),
                ('jobdesc', models.TextField(blank=True, db_column='jobDesc', null=True)),
                ('wopriority', models.CharField(blank=True, db_column='woPriority', max_length=15, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('jobstatus', models.CharField(blank=True, db_column='jobStatus', max_length=50, null=True)),
                ('statusupdatedat', models.DateTimeField(db_column='statusUpdatedAt', default=django.utils.timezone.now)),
                ('refdomainid', models.ForeignKey(blank=True, db_column='refDomainId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Domain')),
                ('refpersonid', models.ForeignKey(blank=True, db_column='refPersonId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Person')),
            ],
            options={
                'db_table': 'workorder',
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('updateid', models.AutoField(db_column='updateId', primary_key=True, serialize=False)),
                ('updatetext', models.TextField(blank=True, db_column='updateText', null=True)),
                ('internalnote', models.TextField(blank=True, db_column='internalNote', null=True)),
                ('updateat', models.DateTimeField(db_column='updateAt', default=django.utils.timezone.now)),
                ('refwoid', models.ForeignKey(blank=True, db_column='refWoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Workorder')),
            ],
            options={
                'db_table': 'updates',
            },
        ),
    ]
