# Generated by Django 2.2.3 on 2019-07-28 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0003_auto_20190728_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': ('add', 'change'), 'verbose_name': '3. Name of the Business/Firm/Entity'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '5. Domain List'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '4. Contact Detail of Person'},
        ),
        migrations.AlterModelOptions(
            name='updates',
            options={'verbose_name': '2. Work Order Updates'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': '1. Create Work Order'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='custaddress',
            field=models.TextField(blank=True, db_column='custAddress', null=True, verbose_name="Customer's Addresss"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custcontact',
            field=models.CharField(blank=True, db_column='custContact', max_length=50, null=True, verbose_name='Phone Number(s)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custemail',
            field=models.CharField(blank=True, db_column='custEmail', max_length=140, null=True, verbose_name='E-Mail ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custisactive',
            field=models.CharField(choices=[('yes', 'Active'), ('no', 'Inactive')], db_column='custIsActive', max_length=3, verbose_name="Customer's Status"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custname',
            field=models.TextField(blank=True, db_column='custName', null=True, verbose_name="Customer's Name"),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domainaddress',
            field=models.CharField(blank=True, db_column='domainAddress', max_length=250, null=True, verbose_name='Domain Address'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domainrefcustid',
            field=models.ForeignKey(blank=True, db_column='domainRefCustId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Customer', verbose_name='Domain Mapped to Customer ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personactive',
            field=models.CharField(choices=[('yes', 'Active'), ('nno', 'Inactive')], db_column='personActive', max_length=3, verbose_name='Is person Active?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personcontact',
            field=models.CharField(blank=True, db_column='personContact', max_length=100, null=True, verbose_name='Contact Email/Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personcontacttype',
            field=models.CharField(blank=True, db_column='personContactType', max_length=5, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personname',
            field=models.CharField(blank=True, db_column='personName', max_length=100, null=True, verbose_name="Person's Name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='personrefcustid',
            field=models.ForeignKey(blank=True, db_column='personRefCustId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Customer', verbose_name='Mapped to Customer ID'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='internalnote',
            field=models.TextField(blank=True, db_column='internalNote', null=True, verbose_name='Internal Note'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='refwoid',
            field=models.ForeignKey(blank=True, db_column='refWoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Workorder', verbose_name='Reference to WorkOrder ID'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='updateat',
            field=models.DateTimeField(db_column='updateAt', default=django.utils.timezone.now, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='updatetext',
            field=models.TextField(blank=True, db_column='updateText', null=True, verbose_name='Update Note for Customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='createdat',
            field=models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now, verbose_name='Work Order Created At'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='jobdesc',
            field=models.TextField(blank=True, db_column='jobDesc', null=True, verbose_name='Description of Work'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='jobstatus',
            field=models.CharField(blank=True, choices=[('working', 'In Progress'), ('completed', 'Completed'), ('finished', 'Finished'), ('awaiting', 'Awaiting For Reply')], db_column='jobStatus', max_length=50, null=True, verbose_name='Current Job Status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='refdomainid',
            field=models.ForeignKey(blank=True, db_column='refDomainId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Domain', verbose_name='Reference Domain ID'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='refpersonid',
            field=models.ForeignKey(blank=True, db_column='refPersonId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Person', verbose_name='Reference By Person ID'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='statusupdatedat',
            field=models.DateTimeField(db_column='statusUpdatedAt', default=django.utils.timezone.now, verbose_name='Status Update Date/Time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wopriority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('sos', 'SOS/Very Urgent')], db_column='woPriority', max_length=15, null=True, verbose_name='Priority of the Work'),
        ),
    ]
