# Generated by Django 2.2.3 on 2019-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0004_auto_20190729_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Name of the Business/Firm/Entity', 'verbose_name_plural': 'Name of the Business/Firm/Entity'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain List'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Contact Detail of Person'},
        ),
        migrations.AlterModelOptions(
            name='updates',
            options={'verbose_name': 'Work Order Update'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Work Order'},
        ),
        migrations.AlterField(
            model_name='person',
            name='personactive',
            field=models.CharField(choices=[('yes', 'Active'), ('no', 'Inactive')], db_column='personActive', max_length=3, verbose_name='Is person Active?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personcontacttype',
            field=models.CharField(choices=[('email', 'E-Mail Address'), ('phone', 'Phone/Mobile Number')], db_column='personContactType', default='email', max_length=5, null=True, verbose_name='Contact Type'),
        ),
    ]
