# Generated by Django 2.2.3 on 2019-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0005_auto_20190729_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='refdomainid',
        ),
        migrations.AddField(
            model_name='workorder',
            name='refdomainid',
            field=models.ManyToManyField(db_column='refDomainId', to='workorderapp.Domain', verbose_name='Select Domains'),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='refpersonid',
        ),
        migrations.AddField(
            model_name='workorder',
            name='refpersonid',
            field=models.ManyToManyField(db_column='refPersonId', to='workorderapp.Person', verbose_name='Multiple Reference'),
        ),
    ]
