# Generated by Django 2.2.3 on 2019-07-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0006_auto_20190730_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='refdomainid',
            field=models.ForeignKey(blank=True, db_column='refDomainId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorderapp.Domain', verbose_name='Reference Domain ID'),
        ),
    ]
