# Generated by Django 2.2.3 on 2019-07-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0008_auto_20190730_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'verbose_name': 'Work Order Update'},
        ),
    ]
