# Generated by Django 2.2.3 on 2019-07-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0009_auto_20190731_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='worktype',
            field=models.CharField(choices=[('paid', 'Paid'), ('maintenance', 'Maintenance'), ('unpaid', 'Unpaid/Free Work'), ('amc', 'Annual Maintenance')], db_column='workType', default='amc', max_length=15, verbose_name='Work Type'),
        ),
    ]
