# Generated by Django 2.2.3 on 2019-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0010_workorder_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='jobstatus',
            field=models.CharField(blank=True, choices=[('working', 'In Progress'), ('completed', 'Completed'), ('finished', 'Finished'), ('awaiting', 'Awaiting For Reply'), ('resolved', 'Resolved')], db_column='jobStatus', max_length=50, null=True, verbose_name='Current Job Status'),
        ),
    ]
