# Generated by Django 2.2.3 on 2019-08-02 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorderapp', '0011_auto_20190731_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='eta',
            field=models.DateTimeField(db_column='etaForWorkOrder', default=django.utils.timezone.now, verbose_name='Estimated Time to Complete'),
        ),
    ]
